# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-09 05:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlchemyCommon', '0007_auto_20160227_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='name',
            field=models.CharField(default='Unknown element', max_length=50, unique=True),
        ),
    ]
