# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-30 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlchemyCommon', '0008_auto_20160726_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='activationToken',
            field=models.TextField(default='qwe'),
            preserve_default=False,
        ),
    ]
