# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-07 15:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AlchemyCommon', '0009_userprofile_activationtoken'),
        ('AlchemyCommon', '0008_auto_20160809_0544'),
    ]

    operations = [
    ]
