# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-23 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlchemyCommon', '0011_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='title',
        ),
        migrations.AddField(
            model_name='report',
            name='screenshot',
            field=models.ImageField(blank=True, upload_to='report_screenshots/'),
        ),
        migrations.AlterField(
            model_name='report',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
