# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-26 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlchemyCommon', '0013_report_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='accepted',
            field=models.NullBooleanField(),
        ),
    ]
